name: Monorepo CI/CD

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-test-build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint
        continue-on-error: true

      - name: Run Tests
        run: npm test
        continue-on-error: true

      - name: Build frontend
        run: npm run build

  lint-test-build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint
        continue-on-error: true

      - name: Run Tests
        run: npm test
        continue-on-error: true

      - name: Build backend
        run: npm run build